# Generated by Django 3.0.8 on 2020-08-11 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=5000)),
                ('type_view', models.CharField(blank=True, choices=[('fio', 'ФИО'), ('pseudo_name', 'Псевдоним')], max_length=11, null=True, verbose_name='Тип представления')),
                ('pseudoname', models.CharField(blank=True, max_length=150, null=True, verbose_name='Псевдоним ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
