# Generated by Django 3.0.8 on 2020-08-10 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Имя автора')),
                ('surname', models.CharField(max_length=35, verbose_name='Фамилия ')),
                ('date_birth', models.DateField(verbose_name='Дата рождения')),
                ('date_dead', models.DateField(blank=True, null=True, verbose_name='Дата смерти')),
                ('bio', models.TextField(max_length=5000, verbose_name='Био автора')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=1000)),
                ('price', models.FloatField()),
                ('is_sale', models.BooleanField(default=False)),
                ('new_price', models.FloatField(blank=True, null=True)),
                ('genre', models.CharField(choices=[('comedy', 'Комедия'), ('trag', 'Боевик'), ('melodrama', 'Драма'), ('futur', 'Фанатаска')], max_length=100)),
                ('author', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='testlesson.Author')),
            ],
        ),
    ]
